controller:
  serviceType: LoadBalancer
  serviceAccount:
    useDefault: false
    create: true
    name: jenkins

rbac:
  create: true
  readSecrets: true

agent:
  serviceAccount:
    create: false
    name: jenkins
    useDefault: false
  rbac:
    create: true
    clusterAdminRole: true

  admin:
    password: "Qwerty123"